export const gameInfos: GameInfo[] = [
	{ title: 'Moonlit Sorcery', age: 4, rating: 1.2, completionTime: 1, difficulty: 1 },
	{ title: 'Chronicles of the Lost Planet', age: 6, rating: 2.6, completionTime: 2, difficulty: 2 },
	{ title: 'The Wizard’s Enigma', age: 8, rating: 3.2, completionTime: 3, difficulty: 3 },
	{ title: 'Ghosts of the Nebula', age: 10, rating: 4.8, completionTime: 4, difficulty: 1 },
	{
		title: 'Dragons in the Ether and other stuff to make it longer',
		age: 12,
		rating: 4.9,
		completionTime: 5,
		difficulty: 2,
	},
	{ title: 'Echoes from the Abyss', age: 14, rating: 1.9, completionTime: 6, difficulty: 3 },
	{ title: 'Forgotten Realms Reclaimed', age: 16, rating: 2.7, completionTime: 7, difficulty: 1 },
	{ title: 'Celestial Knights', age: 18, rating: 3.6, completionTime: 8, difficulty: 2 },
	{ title: 'Quest for the Mystic Relic', age: 4, rating: 4.1, completionTime: 9, difficulty: 3 },
	{ title: 'Guardians of the Starlight', age: 6, rating: 4.4, completionTime: 10, difficulty: 1 },
	{ title: 'Serpent’s Scale', age: 8, rating: 1.9, completionTime: 11, difficulty: 2 },
	{ title: 'Temporal Nexus', age: 10, rating: 2.9, completionTime: 12, difficulty: 3 },
	{ title: 'Winds of the Elders', age: 12, rating: 3.3, completionTime: 1, difficulty: 1 },
	{ title: 'Eclipsing Shadows', age: 14, rating: 4.5, completionTime: 2, difficulty: 2 },
	{ title: 'Oaths in the Dark', age: 16, rating: 4.6, completionTime: 3, difficulty: 3 },
];
